export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  SET_UID: "SET_UID",
  SET_USER: "SET_USER",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  SET_ALL_USERS: "SET_ALL_USERS",
  ADD_CART_PRODUCT: "ADD_CART_PRODUCT",

  ADD_IMAGE: "ADD_IMAGE",
  ADD_THUMBNAIL: "ADD_THUMBNAIL",
  ADD_IMAGE_LINKS: "ADD_IMAGE_LINKS",

  SET_SELL_PRODUCTS_BY_USER: "SET_SELL_PRODUCTS_BY_USER",
  SET_SELL_PRODUCTS_BY_ANOTHER_USER: "SET_SELL_PRODUCTS_BY_ANOTHER_USER",
  SET_SELL_PRODUCTS: "SET_SELL_PRODUCTS",
  GET_SINGLE_SELL_PRODUCT: "GET_SINGLE_SELL_PRODUCT",
};
