export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  SET_UID: "SET_UID",
  SET_USER: "SET_USER",
  ADD_CART_PRODUCT: "ADD_CART_PRODUCT",

  ADD_PROFILE_PIC: "ADD_PROFILE_PIC",

  SET_SELL_PRODUCTS_BY_USER: "SET_SELL_PRODUCTS_BY_USER",
  SET_SELL_PRODUCTS: "SET_SELL_PRODUCTS",
};
